function startOutil
%STARTOUTIL - Interface graphique de l'outil de gestion
%             du plant de production d'ammoniac.


% creation du cadre
handles(1)=figure('units','pixels',...
    'position',[700 300 600 500],...
    'color',[0.935 0.95 0.657],...
    'numbertitle','off',...
    'name','Outil de gestion du plan d''ammoniac',...
    'menubar','none');

% flux de NH3
uicontrol ( 'style' , ' text' , 'units',...
    'normalized', 'position', [0.1,0.8,0.38,0.05] ,...
    'backgroundcolor','g','fontsize',15,'fontname','roman',...
    'string' , 'Quantite de NH3 [t/jour]' );
mNH3= uicontrol ( 'style' , 'edit' ,...
    'fontname','arial','fontsize',15,...
    'units','normalized', 'position', [0.5,0.8,0.2,0.06] ,...
    'string' , '1500' );

%%%%%%%%%% DONNEES %%%%%%%%%%

uicontrol ( 'style' , ' text' , 'units',...
    'normalized', 'position', [0.,0.7,0.3,0.05] ,...
    'backgroundcolor','m','fontsize',15,'fontname','roman',...
    'string' , 'Reformeur primaire' );
% temperature du reformer primaire
uicontrol ( 'style' , ' text' , 'units',...
    'normalized', 'position', [0.1,0.6,0.38,0.05] ,...
    'backgroundcolor','g','fontsize',15,'fontname','roman',...
    'string' , 'Temperature [K]' );
tRef1= uicontrol ( 'style' , 'edit' ,...
    'fontname','arial','fontsize',15,...
    'units','normalized', 'position', [0.5,0.6,0.2,0.06] , ...
    'string' , '1000' );

% pression du reformer primaire
uicontrol ( 'style' , ' text' , 'units',...
    'normalized', 'position', [0.1,0.5,0.38,0.05] ,...
    'backgroundcolor','g','fontsize',15,'fontname','roman',...
    'string' , 'Pression [bar]' );
pRef1= uicontrol ( 'style' , 'edit' ,...
    'fontname','arial','fontsize',15,...
    'units','normalized', 'position', [0.5,0.5,0.2,0.06] ,...
    'string' , '26' );

%%%%%%%%%% BOUTONS %%%%%%%%%%

% analyse parametrique
uicontrol('style','pushbutton',... 
    'units','normalized',...
    'position',[0.1 0.34 0.3 0.06],...
    'string','Analyse parametrique',...    
    'fontsize',13',...
    'callback',@analyseParam);

% analyse environnementale
uicontrol('style','pushbutton',... 
    'units','normalized',...
    'position',[0.1 0.26 0.3 0.06],...
    'string','Analyse environnementale',...    
    'fontsize',13',...
    'callback',@analyseEnv);

% 
uicontrol('style','pushbutton',... 
    'units','normalized',...
    'position',[0.1 0.18 0.3 0.06],...
    'string','Reacteur de synthese',...    
    'fontsize',13',...
    'callback',@syntheseReac);

% refroidissement
uicontrol('style','pushbutton',... 
    'units','normalized',...
    'position',[0.1 0.1 0.3 0.06],...
    'string','Refroidissement',...    
    'fontsize',13',...
    'callback',@printRefroidissement);

% printMasses
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.6 0.27 0.28 0.06],...
    'string','Print flux [tonnes/jour]',...  
    'fontsize',13',...
    'callback',{@printMasses,'t'});

% printMoles
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.6 0.17 0.28 0.06],...
    'string','Print flux [moles/s]',... 
    'fontsize',13',...
    'callback',{@printMasses,'m'});

% informations
action=uicontrol ( 'style' , ' text' , 'units',...
    'normalized', 'position', [0.05,0.9,0.92,0.05] ,...
    'backgroundcolor','k','foregroundcolor','w','fontsize',15,'fontname','roman',...
    'string' , 'Hello !' );

% stop
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.1 0.01 0.8 0.06],...
    'string','STOP',...  
    'fontsize',13',...
    'callback',@stopAll);

%%%%%%%%%% FONCTIONS %%%%%%%%%%

function printMasses(~,~,var)
    m_nh3 = str2double(get(mNH3,'string'));
    T     = str2double(get(tRef1,'string'));
    p_ref1= str2double(get(pRef1,'string'));
    main(m_nh3,T,p_ref1,var);
    if var=='t'
        set(action,'String','Flux en tonnes/jour : done');
    else
        set(action,'String','Flux en moles/secondes : done'); 
    end
end

function analyseParam(~,~)
    p_ref1= str2double(get(pRef1,'string'));  
    analyseParametrique(p_ref1);
    set(action,'String','Analyse parametrique : done');
end

function analyseEnv(~,~)
    environnement;
    set(action,'String','Analyse environnementale : done');
end

function syntheseReac(~,~)
    efficiencePlot; 
    set(action,'String','Conditions optimales du reacteur de synthese : done');
end

function printRefroidissement(~,~)
	m_nh3 = str2double(get(mNH3,'string'));
	nbLitres = refroidissement(m_nh3);
	fprintf('\nIl faut %d [litres/s] pour refroidir les reacteurs de synthese.\n',...
        nbLitres);
    set(action,'String','Refroidissement : done');
end

function stopAll(~,~)
    close 'Outil de gestion du plan d''ammoniac'
end


end

